version: '2'
services:
  locator:
    image: boriza/gemfire-locator:latest
    build: locator/
    ports:
     - "41111:41111"
     - "1099:1099"
    extra_hosts:
     - "locatorhost:172.16.111.2"
    networks:
      gemfire_net:
        ipv4_address: 172.16.111.2
  server:
    image: boriza/gemfire-server:latest
    build: server/
    depends_on:
     - locator
    ports:
     - "40404:40404"
    extra_hosts:
     - "locatorhost:172.16.111.2"
    networks:
      gemfire_net:
        ipv4_address: 172.16.111.3
  # client:
  #   image: boriza/gemfire-client:latest
  #   build: client/
  #   depends_on:
  #    - server
  #   extra_hosts:
  #    - "locatorhost:172.16.111.2"
  #   networks:
  #     gemfire_net:
  #       ipv4_address: 172.16.111.4
networks:
  gemfire_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.111.0/24
        gateway: 172.16.111.1
